CREATE TABLE IF NOT EXISTS "File" (
	"Name" TEXT NOT NULL,
	"Content" BLOB NOT NULL,
	"Size" INTEGER NOT NULL,
	"Created" INTEGER NULL,
	PRIMARY KEY("Name")
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS "Store" (
	"Key" TEXT NOT NULL,
	"Value" BLOB NOT NULL,
	PRIMARY KEY("Key")
) WITHOUT ROWID;
